In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('hepatitis.csv')
df

,2,30,2.1,1,2.2,2.3,2.4,2.5,1.1,2.6,2.7,2.8,2.9,2.10,1.2,85,18,4,?,1.3
0,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.9,135,42,3.5,?,1
1,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.7,96,32,4,?,1
2,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.7,46,52,4,80,1
3,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1,?,200,4,?,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.9,95,28,4,75,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.6,?,242,3.3,50,2
150,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.9,126,142,4.3,?,2
151,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.8,75,20,4.1,?,2
152,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.5,81,19,4.1,48,2
153,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.2,100,19,3.1,42,2

In [3]:
cols=['CLASS','AGE','SEX','STEROID','ANTIVIRALS','FATIGUE','MALAISE','ANOREXIA','LIVER BIG','LIVER FIRM','SPLEEN PALPABLE','SPIDERS','ASCITES','VARICES','BILIRUBIN','ALK PHOSPHATE','SGOT','ALBUMIN','PROTIME','HISTOLOGY']

In [4]:
df.columns=cols

In [5]:
df

,CLASS,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.9,135,42,3.5,?,1
1,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.7,96,32,4,?,1
2,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.7,46,52,4,80,1
3,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1,?,200,4,?,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.9,95,28,4,75,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.6,?,242,3.3,50,2
150,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.9,126,142,4.3,?,2
151,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.8,75,20,4.1,?,2
152,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.5,81,19,4.1,48,2
153,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.2,100,19,3.1,42,2

# 1

In [6]:
df.isna().sum()

CLASS              0
AGE                0
SEX                0
STEROID            0
ANTIVIRALS         0
FATIGUE            0
MALAISE            0
ANOREXIA           0
LIVER BIG          0
LIVER FIRM         0
SPLEEN PALPABLE    0
SPIDERS            0
ASCITES            0
VARICES            0
BILIRUBIN          0
ALK PHOSPHATE      0
SGOT               0
ALBUMIN            0
PROTIME            0
HISTOLOGY          0
dtype: int64

In [7]:
df.dropna(inplace=True)
df

,CLASS,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.9,135,42,3.5,?,1
1,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.7,96,32,4,?,1
2,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.7,46,52,4,80,1
3,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1,?,200,4,?,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.9,95,28,4,75,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.6,?,242,3.3,50,2
150,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.9,126,142,4.3,?,2
151,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.8,75,20,4.1,?,2
152,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.5,81,19,4.1,48,2
153,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.2,100,19,3.1,42,2

In [8]:
df.replace('?',np.nan,inplace=True)
df

,CLASS,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.9,135,42,3.5,NaN,1
1,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.7,96,32,4,NaN,1
2,2,31,1,NaN,1,2,2,2,2,2,2,2,2,2,0.7,46,52,4,80,1
3,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1,NaN,200,4,NaN,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.9,95,28,4,75,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.6,NaN,242,3.3,50,2
150,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.9,126,142,4.3,NaN,2
151,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.8,75,20,4.1,NaN,2
152,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.5,81,19,4.1,48,2
153,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.2,100,19,3.1,42,2

In [9]:
df.replace('NaN',df.mean(),inplace=True)
df

,CLASS,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.9,135,42,3.5,NaN,1
1,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.7,96,32,4,NaN,1
2,2,31,1,NaN,1,2,2,2,2,2,2,2,2,2,0.7,46,52,4,80,1
3,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1,NaN,200,4,NaN,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.9,95,28,4,75,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,1,46,1,2,2,1,1,1,2,2,2,1,1,1,7.6,NaN,242,3.3,50,2
150,2,44,1,2,2,1,2,2,2,1,2,2,2,2,0.9,126,142,4.3,NaN,2
151,2,61,1,1,2,1,1,2,1,1,2,1,2,2,0.8,75,20,4.1,NaN,2
152,2,53,2,1,2,1,2,2,2,2,1,1,2,1,1.5,81,19,4.1,48,2
153,1,43,1,2,2,1,2,2,2,2,1,1,1,2,1.2,100,19,3.1,42,2

In [10]:
df.dropna(inplace=True)
df=df.astype(float)
df

,CLASS,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
4,2.0,34.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.9,95.0,28.0,4.0,75.0,1.0
9,2.0,39.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.3,78.0,30.0,4.4,85.0,1.0
10,2.0,32.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,59.0,249.0,3.7,54.0,1.0
11,2.0,41.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,0.9,81.0,60.0,3.9,52.0,1.0
12,2.0,30.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.2,57.0,144.0,4.9,78.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2.0,45.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.3,85.0,44.0,4.2,85.0,2.0
142,1.0,49.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.4,85.0,70.0,3.5,35.0,2.0
144,2.0,31.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.2,75.0,173.0,4.2,54.0,2.0
152,2.0,53.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.5,81.0,19.0,4.1,48.0,2.0
153,1.0,43.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.2,100.0,19.0,3.1,42.0,2.0

# 2

In [11]:
zv=np.abs((df-df.mean())/df.std())
out=zv >3
df=df[~out.any(axis=1)]
df

,CLASS,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
4,2.0,34.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.9,95.0,28.0,4.0,75.0,1.0
9,2.0,39.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.3,78.0,30.0,4.4,85.0,1.0
10,2.0,32.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,59.0,249.0,3.7,54.0,1.0
11,2.0,41.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,0.9,81.0,60.0,3.9,52.0,1.0
12,2.0,30.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.2,57.0,144.0,4.9,78.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2.0,45.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.3,85.0,44.0,4.2,85.0,2.0
142,1.0,49.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.4,85.0,70.0,3.5,35.0,2.0
144,2.0,31.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.2,75.0,173.0,4.2,54.0,2.0
152,2.0,53.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.5,81.0,19.0,4.1,48.0,2.0
153,1.0,43.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,1.2,100.0,19.0,3.1,42.0,2.0

 3 USE LABEL-ENCODER XD ;) WRITE YOUR OWN CODE

In [12]:
# Scaler=StandardScaler()
# df=Scaler.fit_transform(df)
# df

In [13]:
# df = df.apply(pd.to_numeric)

# 4

In [14]:
X=df.drop('HISTOLOGY',axis=1)
y=df['HISTOLOGY']

In [15]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=46)

In [16]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression()

In [17]:
a1=reg.predict(x_test)
a1

array([1., 2., 1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1.])

In [18]:
nvg=MultinomialNB()
nvg.fit(x_train,y_train)

MultinomialNB()

In [19]:
a2=nvg.predict(x_test)
a2

array([1., 2., 1., 2., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2., 1.])

In [20]:
nvgg=GaussianNB()
nvgg.fit(x_train,y_train)

GaussianNB()

In [21]:
a3=nvgg.predict(x_test)
a3

array([1., 1., 2., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1.])

In [22]:
z1=accuracy_score(y_test,a1)
z2=accuracy_score(y_test,a2)
z3=accuracy_score(y_test,a3)

In [23]:
print(z1)
print(z2)
print(z3)

0.5333333333333333
0.6
0.8666666666666667

# end